### ISSUE TITLE
IntroJS - Trouble adding additional widgets to config file

### ISSUE THREAD

**Issue by dwoodinnovate** [AdriSolid/WAB-Custom-Widgets#2]
Hello,
    Firstly I want to say thank you so much for this port of the introJS library for use in the WAB! I wondered if you could help me with an app that I am setting up. I have many additional widgets and I can't seem to find a way to adjust your config file to point to them. See screenshot.
![image](https://user-images.githubusercontent.com/11931923/42598869-4ee54eba-8512-11e8-9cf0-ff6b2e22db21.png)
If you notice this element has a (settingid="widgets_About_Widget_47") element but if I add this to the config file like so:
![image](https://user-images.githubusercontent.com/11931923/42599016-c93445a4-8512-11e8-8c9c-788d3f322e1e.png)
 the introJS window pop's up in the middle of the screen. 
![image](https://user-images.githubusercontent.com/11931923/42599056-ea884296-8512-11e8-9cd4-c97f722668f1.png)
Any ideas?

**Comment by AdriSolid** [comment]
Hello :)

Try to get the node by 'title', like this: getNode('[title="Change Log"]')

Cheers

**Comment by dwoodinnovate** [comment]
Thank you for the reply. This solution wasn't quite what I needed but it guided me to the solution. 

the Title is used in two places in the WAB. So InroJS selected the title text in the widget itself. 
![image](https://user-images.githubusercontent.com/11931923/43169926-c38c8860-8f57-11e8-87f2-6d70f4214637.png)

If the widget is closed the IntroJS window sits in the upper left corner.
![image](https://user-images.githubusercontent.com/11931923/43169969-ec233d78-8f57-11e8-8ba5-caf7a3f563b2.png)

So using your suggestion I tried getNode('[settingid="widgets_About_Widget_47"]') and got the desired outcome. 

![image](https://user-images.githubusercontent.com/11931923/43169819-5f5d069e-8f57-11e8-8c5e-24565a546cfd.png)

**Comment by AdriSolid** [comment]
Cool! I'm gonna add it in my readme!

Best
